### ISSUE TITLE
Ns in DNAstringset greys out all text in console that follows

### ISSUE THREAD

**Issue by proychou** [Bioconductor/Biostrings#54] opened 2021-08-16 13:53 UTC
This is minor and only affects visualization in the R/Rstudio console window. 

I love the base colouring in the console. But I noticed that if there are Ns in a sequence, it causes all subsequent text to be greyed out.

```
#this looks fine
myfasta<-DNAStringSet(x=c('ACTG','GGGG'))
myfasta
print('Hi, can you see me?')

#this greys out
myfasta<-DNAStringSet(x=c('ACTG','NN','GGGG'))
myfasta
print('Hi, can you see me?')
```

**Comment by hpages** [comment] 2021-08-16 19:06
Hi Pavitra, nice to see you here!

I can't reproduce this. See my screenshot (using Docker image `bioconductor_docker:devel` as instructed [here](https://bioconductor.org/help/docker/)):

![Screenshot from 2021-08-16 11-52-50](https://user-images.githubusercontent.com/8810451/129616375-26aa4e3a-636b-4e03-961b-1fa47f14dd8f.png)

Note that **Biostrings** uses the **crayon** package (from CRAN) internally to produce the colored letters. I wonder if you are able to reproduce the issue with this simple code:
```
library(crayon)
whiter <- make_style(rgb(1, 1, 1))
colored_N <- make_style("grey", bg=TRUE)(whiter("N"))
cat(colored_N, "\n")
print('Hi, can you see me?')
```
or with this even simpler code:
```
library(crayon)
colored_N <- make_style("grey", bg=TRUE)("N")
cat(colored_N, "\n")
print('Hi, can you see me?')
```
If that is the case, then it would be an indication that the problem originates from a bad interaction between the **crayon** package and your RStudio setup. In which case you might want to try reporting this to the **crayon** maintainer: https://github.com/r-lib/crayon/issues.

Kind regards,
H.

**Comment by hpages** [comment] 2021-09-23 22:28
Hi Pavitra,

Where you able to solve this? Or to report the issue to the **crayon** maintainer?

I will close this issue next week if I don't hear back from you.

Thanks,
H.

**Comment by proychou** [comment] 2021-09-27 12:09
Hi Hervé!

I'm so sorry I missed this.. notification went to spam. Apologies.

Here's what those look like on mine: 
<img width="359" alt="Screen Shot 2021-09-27 at 5 06 04 AM" src="https://user-images.githubusercontent.com/9486105/134905006-d9ad114c-3cba-483e-ae45-b76d61fe4c99.png">
and 
<img width="327" alt="Screen Shot 2021-09-27 at 5 06 18 AM" src="https://user-images.githubusercontent.com/9486105/134905044-fb0d49d3-44b8-4f26-8bfd-77713f6c4aeb.png">

And my original example: 
<img width="339" alt="Screen Shot 2021-09-27 at 5 05 36 AM" src="https://user-images.githubusercontent.com/9486105/134905157-9cad2edd-ec9a-44c4-bc51-7f9b671d15b5.png">

I'll report to the crayon maintainer. Thanks for responding! 

Pavitra

**Comment by hpages** [comment] 2021-09-28 18:56
No problem. Thanks for reporting to the crayon maintainer.

H.

**Closed** 2022-10-29 02:08 UTC
